obstacle_range: 2.5
raytrace_range: 5.0
footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]
inflation_radius: 0.5
cost_scaling_factor: 20.0 
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

