DWAPlannerROS:
  max_vel_x: 0.06
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_theta: 0.3
  min_vel_theta: -0.3
  acc_lim_x: 1.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  yaw_goal_tolerance: 0.01
  xy_goal_tolerance: 0.1
  sim_time: 5
  sim_granularity: 0.025
  vx_samples: 3
  vy_samples: 0
  vtheta_samples: 20
  path_distance_bias: 100.0
  goal_distance_bias: 70.0
  occdist_scale: 0.05
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom
  oscillation_reset_dist: 0.05

  